# Generated by Django 5.1.6 on 2025-02-15 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('instructor', models.CharField(max_length=255)),
                ('duration', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rating', models.FloatField()),
                ('reviews', models.IntegerField()),
                ('category', models.CharField(blank=True, choices=[('Bestseller', 'Bestseller'), ('Top Author', 'Top Author'), ('Most Popular', 'Most Popular'), ("Editor's Choice", "Editor's Choice")], max_length=50, null=True)),
                ('image', models.ImageField(upload_to='course_images/')),
            ],
        ),
    ]
