# Generated by Django 5.1.6 on 2025-02-21 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='discount',
            new_name='discount_percent',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='original_price',
        ),
    ]
