# Generated by Django 5.1.6 on 2025-02-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='original_price',
        ),
        migrations.AddField(
            model_name='course',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
