# Generated by Django 5.1.4 on 2024-12-19 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0003_alter_addstudent_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=100)),
                ('phone_number', models.IntegerField(max_length=13)),
                ('lecture_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Add_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=200)),
                ('phone_number', models.IntegerField(max_length=13)),
                ('dob', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='AddStudent',
        ),
    ]
