# Generated by Django 5.1.4 on 2024-12-19 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0004_add_staff_add_student_delete_addstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='add_staff',
            name='email_id',
        ),
        migrations.RemoveField(
            model_name='add_staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='add_staff',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='add_staff',
            name='lecture_time',
        ),
        migrations.RemoveField(
            model_name='add_staff',
            name='phone_number',
        ),
    ]
