# Generated by Django 5.1.4 on 2024-12-19 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0005_remove_add_staff_email_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_student',
            name='phone_number',
            field=models.CharField(max_length=13),
        ),
    ]
