# Generated by Django 5.1.4 on 2024-12-19 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0006_alter_add_student_phone_number'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Add_Staff',
        ),
    ]
