# Generated by Django 5.1.4 on 2024-12-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lmsapp', '0007_delete_add_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Add_Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('staff_first_name', models.CharField(max_length=100)),
                ('staff_last_name', models.CharField(max_length=100)),
                ('staff_email_id', models.EmailField(max_length=200)),
                ('staff_phone_number', models.CharField(max_length=13)),
                ('lecture_time', models.DateTimeField()),
            ],
        ),
    ]
