# Generated by Django 5.1 on 2025-01-31 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('std', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='folder',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('test_type', models.CharField(choices=[('quiz', 'Quiz'), ('document', 'Document'), ('qa', 'Q/A'), ('link', 'Link'), ('combined', 'Combined')], max_length=50)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='std.batch')),
            ],
        ),
    ]
